# Generated by Django 3.1 on 2022-10-27 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20221027_2227'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_remove_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(blank=True, related_name='user_order', through='orders.Order', to=settings.AUTH_USER_MODEL, verbose_name='상품 주문내역'),
        ),
    ]
