# Generated by Django 3.1 on 2022-10-27 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='상품 주문 수량')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('receiver_name', models.CharField(max_length=40, verbose_name='수령자이름')),
                ('receiver_phone_number', models.CharField(help_text='휴대폰 번호는 다음과 같은 형식을 따라야 합니다: 010-1234-5678', max_length=13, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')])),
                ('order_state', models.CharField(choices=[('주문취소', 0), ('주문완료', 1)], default='주문완료', max_length=4, verbose_name='주문서 상태')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='주문 날짜')),
                ('total_price', models.PositiveIntegerField(null=True, verbose_name='주문서 총 가격')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'db_table': 'order',
            },
        ),
    ]
