# Generated by Django 3.1 on 2022-10-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_order'),
        ('orders', '0002_auto_20221027_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_quantity',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sub_total_price', models.PositiveIntegerField(null=True, verbose_name='주문 상품 가격')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='products.product')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품 목록',
                'db_table': 'orderitem',
            },
        ),
    ]
