# Generated by Django 3.1 on 2022-10-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221023_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('주문취소', 0), ('주문완료', 1)], default='주문완료', max_length=4, verbose_name='주문서 상태'),
        ),
    ]
