# Generated by Django 3.1 on 2022-10-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_order'),
        ('orders', '0005_auto_20221027_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='상품 주문 수량'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
