# Generated by Django 3.1 on 2022-10-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20221023_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='상품 주문 수량'),
        ),
    ]
